apiVersion: batch/v1
kind: Job
metadata:
  name: erda-upgrade-job
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-upgrade
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
        - env:
            - name: MIGRATION_MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: dice-addons-info
                  key: MYSQL_HOST
            - name: MIGRATION_MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: dice-addons-info
                  key: MYSQL_PASSWORD
            - name: MIGRATION_MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: dice-addons-info
                  key: MYSQL_PORT
            - name: MIGRATION_MYSQL_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: dice-addons-info
                  key: MYSQL_USERNAME
            - name: MIGRATION_MYSQL_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: dice-addons-info
                  key: MYSQL_DATABASE
            - name: TZ
              value: Asia/Shanghai
            - name: MIGRATION_DEBUGSQL
              value: "false"
            - name: MIGRATION_ERDA_LINT
              value: "true"
          image:
            {{ .Values.global.image.repository }}/init-image:{{.Values.erda.tags.init}}
          imagePullPolicy: {{.Values.global.image.imagePullPolicy}}
          name: init-image
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      restartPolicy: Never
      serviceAccountName: erda-operator
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
        - effect: NoSchedule
          key: node-role.kubernetes.io/lb
