apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: erda-operator
  name: erda-operator
  namespace: {{ .Values.global.namespace | default "erda-system" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: erda-operator
  strategy:
    type: {{ .Values.global.updateStrategy.type | default "RollingUpdate" }}
  template:
    metadata:
      labels:
        app: erda-operator
    spec:
      serviceAccountName: dice-operator
      containers:
      - image: {{ .Values.global.image.repository }}/dice-operator:{{ .Values.erda.operator.tag }}
        imagePullPolicy: {{ .Values.global.image.imagePullPolicy }}
        name: erda-operator
        env:
        - name: ENABLE_SPECIFIED_NAMESPACE
          value: {{ .Values.global.namespace | default "erda-system" }}
        - name: ENABLE_CONFIGMAP_NAMESPACE
          value: {{ .Values.global.namespace | default "erda-system" }}
        {{- if .Values.tags.work }}
        - name: ENABLE_ETCD_SECRET
          value: disable
        {{- end }}
        - name:  INJECT_CLUSTER_INFO
          value: "false"
        - name: ENABLE_AFFINITY
          value: "false"
        - name: ERDA_CLUSTER_INFO
          value: dice-cluster-info
        - name: ERDA_ADDON_INFO
          value: dice-addons-info
        {{- with .Values.erda.operator.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      restartPolicy: Always
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      tolerations:
      - operator: Exists
