apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: erdas.erda.terminus.io
spec:
  group: erda.terminus.io
  names:
    kind: Erda
    plural: erdas
    singular: erda
  scope: Namespaced
  subresources:
    status: {}
  versions:
    - name: v1beta1
      served: true
      storage: true
  additionalPrinterColumns:
    - name: Status
      type: string
      JSONPath: .status.phase
      description: Erda cluster current status
    - name: LastMessage
      type: string
      JSONPath: .status.conditions[0].reason
      description: last message