global:
  namespace: default
  size: demo
  image:
    repository: registry.erda.cloud/erda
    imagePullPolicy: IfNotPresent
  imagePullSecrets: [ ]

tag: 1.0.0-20200608-f11445f
replicas:
resources:
  requests:
    cpu: 0.1
    memory: 10Mi
  limits:
    cpu: 0.5
    memory: 512Mi
