kind: Service
apiVersion: v1
metadata:
  name: erda-sonar
  namespace: {{ .Values.global.namespace | default "erda-system" }}
spec:
  ports:
  - name: erda-sonar-tcp-9000
    protocol: TCP
    port: 9000
  selector:
    dice/addon: erda-sonar
