apiVersion: v1
kind: ConfigMap
metadata:
  name: erda-sonar
  namespace: {{ .Values.global.namespace | default "erda-system" }}
data:
  SONAR_ADMIN_PASSWORD: {{ .Values.password }}
  SONAR_ADMIN_TOKEN: {{ .Values.token }}
