{{- if and .Values.certgen.serviceAccount.create (include "erda.certgen.enabled" .) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "erda.certgen.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.base" . | nindent 4 }}
    app.kubernetes.io/component: erda-certgen
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
{{- end }}