apiVersion: v1
kind: Service
metadata:
  name: erda-kms
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http
      port: 3082
      protocol: TCP
      targetPort: 3082
  selector:
    app.kubernetes.io/name: erda-kms
