{{- if eq .Values.global.size "demo" }}
---
apiVersion: v1
kind: Service
metadata:
  name: erda-etcd
  namespace: {{ .Values.global.namespace | default "erda-system" }}
spec:
  clusterIP: None
  ports:
  - name: etcd-port
    port: 2379
    protocol: TCP
    targetPort: 2379
  - name: etcd-server-port
    port: 2380
    protocol: TCP
    targetPort: 2380
  selector:
    app: erda-etcd
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: erda-etcd
  name: erda-etcd
  namespace: {{ .Values.global.namespace | default "erda-system" }}
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: erda-etcd
  serviceName: erda-etcd
  template:
    metadata:
      labels:
        app: erda-etcd
    spec:
      tolerations:
        - operator: Exists
      containers:
        - name: erda-etcd
          image: {{ .Values.global.image.repository}}/erda-etcd:{{ .Values.tag }}
          imagePullPolicy: IfNotPresent
          env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: HOST_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.hostIP
          command:
          - etcd
          - --enable-pprof=true
          - --advertise-client-urls=https://erda-etcd.{{ .Values.global.namespace | default "erda-system" }}.svc.cluster.local:2379
          - --data-dir=/var/lib/etcd
          - --initial-advertise-peer-urls=https://erda-etcd.{{ .Values.global.namespace | default "erda-system" }}.svc.cluster.local:2380
          - --initial-cluster=erda-etcd=https://erda-etcd.{{ .Values.global.namespace | default "erda-system" }}.svc.cluster.local:2380
          - --listen-client-urls=https://0.0.0.0:2379
          - --listen-metrics-urls=https://0.0.0.0:2381
          - --listen-peer-urls=https://0.0.0.0:2380
          - --name=erda-etcd
          - --snapshot-count=10000
          - --auto-compaction-retention=1
          - --quota-backend-bytes=8589934592
          - --client-cert-auth=true
          - --trusted-ca-file=/etc/kubernetes/ssl/etcd-ca.pem
          - --cert-file=/etc/kubernetes/ssl/etcd-server.pem
          - --key-file=/etc/kubernetes/ssl/etcd-server-key.pem
          - --peer-client-cert-auth=true
          - --peer-trusted-ca-file=/etc/kubernetes/ssl/etcd-ca.pem
          - --peer-cert-file=/etc/kubernetes/ssl/etcd-peer.pem
          - --peer-key-file=/etc/kubernetes/ssl/etcd-peer-key.pem
          ports:
          - containerPort: 2379
            name: client
            protocol: TCP
          - containerPort: 2380
            name: server
            protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 1Gi
          volumeMounts:
          - name: etcd-server-secret
            mountPath: /etc/kubernetes/ssl/
            readOnly: true
          - name: erda-etcd
            mountPath: /var/lib/etcd
      volumes:
        - name: etcd-server-secret
          secret:
            secretName: etcd-server-secret
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      labels:
        app: erda-etcd
      name: erda-etcd
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.capacity | default "16Gi" }}
      storageClassName: {{ .Values.global.storageClassName | default "dice-local-volume" }}
      volumeMode: Filesystem
{{- end }}
