apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app:  erda-etcd
  name:  erda-etcd
  namespace:  {{ .Values.global.namespace | default "erda-system" }}
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app:  erda-etcd
        job-name:  erda-etcd
    spec:
      containers:
      - env:
        - name: ERDA_ETCD_NAME
          value: erda-etcd
        - name: ERDA_NAMESPACE
          value: {{ .Values.global.namespace | default "erda-system" }}
        - name: ERDA_SIZE
          value: {{ .Values.global.size | default "demo" }}
        image: {{ .Values.global.image.repository}}/etcd_ssl_gen:v0.1.0
        imagePullPolicy: IfNotPresent
        name: k8s
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
      dnsPolicy: ClusterFirst
      securityContext: {}
      restartPolicy: "Never"
      serviceAccount: erda-etcd
      serviceAccountName: erda-etcd
