kind: Deployment
apiVersion: apps/v1
metadata:
  name: erda-sonar
  namespace: {{ .Release.Namespace }}
  labels:
    dice/addon: erda-sonar
    erda/addon: erda-sonar
spec:
  replicas: 1
  selector:
    matchLabels:
      dice/addon: erda-sonar
  template:
    metadata:
      labels:
        dice/addon: erda-sonar
        erda/addon: erda-sonar
    spec:
      {{- if eq .Values.global.size "prod" }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: "dice/platform"
                  operator: Exists
      {{- end }}
      containers:
      - name: erda-sonar
        image:  {{ .Values.global.image.repository }}/addon-sonar:{{ .Values.tag }}
        imagePullPolicy: {{ .Values.global.image.imagePullPolicy }}
        ports:
        - containerPort: 9000
          protocol: TCP
        env:
        - name: SONAR_ADMIN_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: SONAR_ADMIN_PASSWORD
              name: erda-sonar
        - name: SONAR_ADMIN_TOKEN
          valueFrom:
            configMapKeyRef:
              key: SONAR_ADMIN_TOKEN
              name: erda-sonar
        - name: DICE_ADDON
          value: erda-sonar
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        resources:
          {{- if eq .Values.global.size "demo" }}
          requests:
            cpu: {{ .Values.resources.requests.cpu | default "100m" | quote }}
            memory: {{ .Values.resources.requests.memory | default "512Mi" | quote }}
          limits:
            cpu: {{ .Values.resources.limits.cpu |  default "500m" | quote }}
            memory: {{ .Values.resources.limits.memory | default "2048Mi" | quote }}
          {{- else }}
          requests:
            cpu: {{ .Values.resources.requests.cpu | default "750m" | quote }}
            memory: {{ .Values.resources.requests.memory | default "1536Mi" | quote }}
          limits:
            cpu: {{ .Values.resources.limits.cpu |  default "1500m" | quote }}
            memory: {{ .Values.resources.limits.memory | default "3Gi" | quote }}
          {{- end }}
        livenessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 1
          timeoutSeconds: 10
          periodSeconds: 15
          successThreshold: 1
          failureThreshold: 9
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
  strategy:
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 100%
