apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    dice/addon: erda-registry
  name: erda-registry
  namespace: {{ .Values.global.namespace | default "erda-system" }}
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      dice/addon: erda-registry
  serviceName: erda-registry
  template:
    metadata:
      labels:
        dice/addon: erda-registry
    spec:
      tolerations:
        - operator: Exists
      containers:
        - name: erda-registry
          image: {{ .Values.global.image.repository }}/addon-registry:{{ .Values.tag }}
          imagePullPolicy: {{ .Values.global.image.imagePullPolicy }}
          ports:
            - containerPort: 5000
              protocol: TCP
              name: port-5000
            - containerPort: 5050
              protocol: TCP
              name: port-5050
          env:
            - name: DICE_ADDON
              value: erda-registry
            - name: REGISTRY_STORAGE_DELETE_ENABLED
              value: 'true'
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | default "0.1" | quote }}
              memory: {{ .Values.resources.requests.memory | default "10Mi" | quote }}
            limits:
              cpu: {{ .Values.resources.limits.cpu |  default "1" | quote }}
              memory: {{ .Values.resources.limits.memory | default "1Gi" | quote }}
          volumeMounts:
            - name: erda-registry
              mountPath: /var/lib/registry
          livenessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 1
            timeoutSeconds: 10
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 9
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        labels:
          dice/addon: erda-registry
        name: erda-registry
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.capacity | default "100Gi" }}
        storageClassName: {{ .Values.global.storageClassName | default "dice-local-volume" }}
        volumeMode: Filesystem