kind: Service
apiVersion: v1
metadata:
  name: erda-registry
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: port-5000
      protocol: TCP
      port: 5000
    - name: port-5050
      protocol: TCP
      port: 5050
  selector:
    dice/addon: erda-registry
