kind: Service
apiVersion: v1
metadata:
  name: erda-registry
  namespace: {{ .Values.global.namespace | default "erda-system" }}
spec:
  ports:
    - name: erda-registry-tcp-5000
      protocol: TCP
      port: 5000
    - name: erda-registry-tcp-5050
      protocol: TCP
      port: 5050
  selector:
    dice/addon: erda-registry
