kind: DaemonSet
apiVersion: apps/v1
metadata:
  labels:
    app: erda-volume-provisioner
  name: erda-volume-provisioner
  namespace: {{ .Values.global.namespace | default "erda-system" }}
spec:
  selector:
    matchLabels:
      app: erda-volume-provisioner
  updateStrategy:
    type: {{ .Values.global.updateStrategy.type | default "RollingUpdate" }}
  template:
    metadata:
      name: erda-volume-provisioner
      labels:
        app: erda-volume-provisioner
    spec:
      serviceAccountName: erda-volume-provisioner
      containers:
        - image:
            {{ .Values.global.image.repository }}/volume-provisioner:{{ .Values.tag }}
          env:
            - name: PROVISIONER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LOCAL_PROVISIONER_NAME
              value: dice/local-volume
            - name: NET_PROVISIONER_NAME
              value: dice/netdata-volume
          imagePullPolicy: Always
          name: erda-volume-provisioner
          volumeMounts:
            - name: host-dir
              mountPath: /hostfs
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: host-dir
          hostPath:
            path: /
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      tolerations:
        - operator: Exists
