kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: erda-volume-provisioner
subjects:
- kind: ServiceAccount
  name: erda-volume-provisioner
  namespace: {{ .Values.global.namespace | default "erda-system" }}
roleRef:
  kind: ClusterRole
  name: erda-volume-provisioner
  apiGroup: rbac.authorization.k8s.io