# Global variable
global:
  # size defines deployment mode: 'demo' for minimal and 'prod' for product.
  size: demo
  # namespace defines which namespace will erda components deployed in Kubernetes.
  namespace: default
  # image defines repository and image pull policy for docker image.
  image:
    # repository defines docker image repository.
    repository: registry.erda.cloud/erda
    # imagePullPolicy defines how to pull images.
    imagePullPolicy: IfNotPresent
  # imagePullSecrets defines pull secrets for pulling image from private image repository.
  imagePullSecrets: [ ]


# operatorImageTag defines cassandra-operator image tag.
operatorImageTag: v1.1.3-release
# cassandraImageTag defines cassandra image tag
cassandraImageTag: 3.11.10
# capacity defines pvc capacity for cassandra instance (default: 1000Gi for prod mode and 50Gi for demo mode)
capacity:
# storageClassName defines which storageclass to use for creating PV in Kubernetes.
storageClassName: "dice-local-volume"
resources:
  requests:
    # cpu defines cpu requests.
    cpu:
    # memory defines memory requests.
    memory:
  limits:
    # cpu defines cpu limits.
    cpu:
    # memory defines memory limits.
    memory:
racks:
  # racks list
  - name: rack1
  - name: rack2
  - name: rack3
