# 全局可用参数
global:
  # 部署模式：支持最小化单点部署（demo） 和 高可用部署（prod） 两种模式
  size: demo
  # 组件部署的目标 namespace，如果不存在需要先创建
  namespace: default
  # 镜像参数
  image:
    # 镜像仓库
    repository: registry.erda.cloud/erda
    # 镜像拉取策略
    imagePullPolicy: IfNotPresent
  # 镜像拉取 Secrets
  imagePullSecrets: [ ]
  # 部署组件中 StatefulSet 负载使用的存储的 StorageClass 对象的名称
  storageClassName:


# cassandra-operator 镜像 tag (版本)
operatorImageTag: v1.1.3-release
# addon-cassandra 镜像 tag (版本)
cassandraImageTag: 3.11.10
# cassandra 节点存储容量
capacity: 1000Gi
resources:
  requests:
    cpu: "6"
    memory: "24Gi"
  limits:
    cpu: "12"
    memory: "48Gi"
# 机架列表，cassandra 部署时按机架分布以提高高可用性
racks:
  # 每个 rack 的名称, rack 的数量决定了高可用部署时 cassandra 实例的副本数量
  - name: rack1
  - name: rack2
  - name: rack3
