apiVersion: "db.orange.com/v1alpha1"
kind: "CassandraCluster"
metadata:
  name: erda-cassandra
  namespace: {{ .Release.Namespace }}
  labels:
    cluster: k8s.kaas
spec:
  cassandraImage: {{ .Values.global.image.repository }}/addon-cassandra:{{ .Values.cassandraImageTag}}
  bootstrapImage: registry.erda.cloud/erda/cassandra-bootstrap:0.1.8
  configMapName: erda-cassandra-configmap-v1
  imagepullpolicy: {{ .Values.global.image.imagePullPolicy }}
  {{- if .Values.global.imagePullSecrets }}
  {{- with .Values.global.imagePullSecrets }}
  imagePullSecret:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- end }}
  dataStorageClass: {{ .Values.storageClassName | default "dice-local-volume" }}
  {{- if eq .Values.global.size "demo" }}
  dataCapacity: {{ .Values.capacity | default "50Gi" }}
  {{- else }}
  dataCapacity: {{ .Values.capacity | default "1000Gi" }}
  {{- end }}
  hardAntiAffinity: true  # ensure only 1 cassandra on each node
  deletePVC: false
  autoPilot: false
  gcStdout: true
  autoUpdateSeedList: false
  maxPodUnavailable: 1
  runAsUser: 999
  backRestSidecar:
    image: registry.erda.cloud/erda/instaclustr-icarus:1.0.9
  resources:
    {{- if eq .Values.global.size "demo" }}
    requests:
      cpu: {{ .Values.resources.requests.cpu | default "100m" | quote }}
      memory: {{ .Values.resources.requests.memory | default "512Mi" }}
    limits:
      cpu: {{ .Values.resources.limits.cpu | default "500m" | quote }}
      memory: {{ .Values.resources.limits.memory | default "2048Mi" }}
    {{- else }}
    requests:
      cpu: {{ .Values.resources.requests.cpu | default "2" | quote }}
      memory: {{ .Values.resources.requests.memory | default "4Gi" }}
    limits:
      cpu: {{ .Values.resources.limits.cpu | default "4" | quote }}
      memory: {{ .Values.resources.limits.memory | default "16Gi" }}
    {{- end}}
  topology:
    dc:
    - name: dc1
      nodesPerRacks: 1
      {{- if eq .Values.global.size "demo" }}
      rack:
      - name: rack1
      {{- else }}
      labels:
        dice/cassandra: ""
        dice/platform: ""
      {{- with .Values.racks }}
      rack:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- end }}
