apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    dice/addon: erda-elasticsearch
  name: erda-elasticsearch
  namespace: {{ .Values.global.namespace | default "erda-system" }}
secrets:
  - name: erda-elasticsearch-token