apiVersion: v1
kind: Service
metadata:
  labels:
    dice/addon: erda-elasticsearch
  name: erda-elasticsearch
  namespace: {{ .Values.global.namespace | default "erda-system" }}
spec:
  ports:
  - name: http
    port: 9200
    protocol: TCP
    targetPort: http
  selector:
    dice/addon: erda-elasticsearch
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    dice/addon: erda-elasticsearch
  name: erda-elasticsearch-master
  namespace: {{ .Values.global.namespace | default "erda-system" }}
spec:
  ports:
  - name: transport
    port: 9300
    protocol: TCP
    targetPort: transport
  selector:
    dice/addon: erda-elasticsearch
  sessionAffinity: None
  type: ClusterIP
