{{- if ne .Values.global.size "demo" }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: erda-zookeeper-1
    erda/addon: erda-zookeeper
  name: erda-zookeeper-1
  namespace: {{ .Release.Namespace }}
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: erda-zookeeper-1
  serviceName: erda-zookeeper-1
  template:
    metadata:
      labels:
        app: erda-zookeeper-1
        erda/addon: erda-zookeeper
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: "dice/zookeeper"
                  operator: Exists
                - key: "dice/platform"
                  operator: Exists
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: erda/addon
                  operator: In
                  values:
                  - erda-zookeeper
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: erda-zookeeper-1
          image: {{ .Values.global.image.repository }}/addon-zookeeper:{{ .Values.tag }}
          imagePullPolicy: {{ .Values.global.image.imagePullPolicy  | default "IfNotPresent" }}
          ports:
          - containerPort: 2181
            protocol: TCP
          - containerPort: 2888
            protocol: TCP
          - containerPort: 3888
            protocol: TCP
          env:
          - name: DICE_PLATFORM_ADDON
            value: erda-zookeeper-1
          - name: ZOO_AUTO_INTERVAL
            value: '2'
          - name: ZOO_AUTO_RETAINCOUNT
            value: '3'
          - name: ZOO_CONF_DIR
            value: "/conf"
          - name: ZOO_DATA_DIR
            value: "/data"
          - name: ZOO_DATA_LOG_DIR
            value: "/datalog"
          - name: ZOO_INIT_LIMIT
            value: '5'
          - name: ZOO_MAX_CLIENT_CNXNS
            value: '60'
          - name: ZOO_MY_ID
            value: '1'
          - name: ZOO_PORT
            value: '2181'
          - name: ZOO_SERVERS
            value: server.2=erda-zookeeper-2.{{ .Release.Namespace }}.svc.cluster.local:2888:3888 server.3=erda-zookeeper-3.{{ .Release.Namespace }}.svc.cluster.local:2888:3888 server.1=0.0.0.0:2888:3888
          - name: ZOO_SYNC_LIMIT
            value: '2'
          - name: ZOO_TICK_TIME
            value: '6000'
          - name: ZOO_USER
            value: zookeeper
          - name: POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: HOST_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.hostIP
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | default "0.1" | quote }}
              memory: {{ .Values.resources.requests.memory | default "256Mi" | quote }}
            limits:
              cpu: {{ .Values.resources.limits.cpu |  default "1" | quote }}
              memory: {{ .Values.resources.limits.memory | default "512Mi" | quote }}
          volumeMounts:
          - name: erda-zookeeper-1
            mountPath: /data
          livenessProbe:
            tcpSocket:
              port: 2181
            initialDelaySeconds: 1
            timeoutSeconds: 10
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 9
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      labels:
        app: erda-zookeeper-1
      name: erda-zookeeper-1
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 32Gi
      storageClassName: {{ .Values.storageClassName | default "dice-local-volume" }}
      volumeMode: Filesystem
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: erda-zookeeper-2
    erda/addon: erda-zookeeper
  name: erda-zookeeper-2
  namespace: {{ .Release.Namespace }}
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: erda-zookeeper-2
  serviceName: erda-zookeeper-2
  template:
    metadata:
      labels:
        app: erda-zookeeper-2
        erda/addon: erda-zookeeper
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: "dice/zookeeper"
                  operator: Exists
                - key: "dice/platform"
                  operator: Exists
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: erda/addon
                  operator: In
                  values:
                  - erda-zookeeper
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: erda-zookeeper-2
          image: {{ .Values.global.image.repository }}/addon-zookeeper:{{ .Values.tag }}
          imagePullPolicy: {{ .Values.global.image.imagePullPolicy  | default "IfNotPresent" }}
          ports:
          - containerPort: 2181
            protocol: TCP
          - containerPort: 2888
            protocol: TCP
          - containerPort: 3888
            protocol: TCP
          env:
          - name: DICE_PLATFORM_ADDON
            value: erda-zookeeper-2
          - name: ZOO_AUTO_INTERVAL
            value: '2'
          - name: ZOO_AUTO_RETAINCOUNT
            value: '3'
          - name: ZOO_CONF_DIR
            value: "/conf"
          - name: ZOO_DATA_DIR
            value: "/data"
          - name: ZOO_DATA_LOG_DIR
            value: "/datalog"
          - name: ZOO_INIT_LIMIT
            value: '5'
          - name: ZOO_MAX_CLIENT_CNXNS
            value: '60'
          - name: ZOO_MY_ID
            value: '2'
          - name: ZOO_PORT
            value: '2181'
          - name: ZOO_SERVERS
            value: server.1=erda-zookeeper-1.{{ .Release.Namespace }}.svc.cluster.local:2888:3888 server.3=erda-zookeeper-3.{{ .Release.Namespace }}.svc.cluster.local:2888:3888 server.2=0.0.0.0:2888:3888
          - name: ZOO_SYNC_LIMIT
            value: '2'
          - name: ZOO_TICK_TIME
            value: '6000'
          - name: ZOO_USER
            value: zookeeper
          - name: POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: HOST_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.hostIP
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | default "0.1" | quote }}
              memory: {{ .Values.resources.requests.memory | default "256Mi" | quote }}
            limits:
              cpu: {{ .Values.resources.limits.cpu |  default "1" | quote }}
              memory: {{ .Values.resources.limits.memory | default "512Mi" | quote }}
          volumeMounts:
          - name: erda-zookeeper-2
            mountPath: /data
          livenessProbe:
            tcpSocket:
              port: 2181
            initialDelaySeconds: 1
            timeoutSeconds: 10
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 9
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      labels:
        app: erda-zookeeper-2
      name: erda-zookeeper-2
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 32Gi
      storageClassName: {{ .Values.storageClassName | default "dice-local-volume" }}
      volumeMode: Filesystem
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: erda-zookeeper-3
    erda/addon: erda-zookeeper
  name: erda-zookeeper-3
  namespace: {{ .Release.Namespace }}
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: erda-zookeeper-3
  serviceName: erda-zookeeper-3
  template:
    metadata:
      labels:
        app: erda-zookeeper-3
        erda/addon: erda-zookeeper
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: "dice/zookeeper"
                  operator: Exists
                - key: "dice/platform"
                  operator: Exists
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: erda/addon
                  operator: In
                  values:
                  - erda-zookeeper
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: erda-zookeeper-3
          image: {{ .Values.global.image.repository }}/addon-zookeeper:{{ .Values.tag }}
          imagePullPolicy: {{ .Values.global.image.imagePullPolicy  | default "IfNotPresent" }}
          ports:
          - containerPort: 2181
            protocol: TCP
          - containerPort: 2888
            protocol: TCP
          - containerPort: 3888
            protocol: TCP
          env:
          - name: DICE_PLATFORM_ADDON
            value: erda-zookeeper-3
          - name: ZOO_AUTO_INTERVAL
            value: '2'
          - name: ZOO_AUTO_RETAINCOUNT
            value: '3'
          - name: ZOO_CONF_DIR
            value: "/conf"
          - name: ZOO_DATA_DIR
            value: "/data"
          - name: ZOO_DATA_LOG_DIR
            value: "/datalog"
          - name: ZOO_INIT_LIMIT
            value: '5'
          - name: ZOO_MAX_CLIENT_CNXNS
            value: '60'
          - name: ZOO_MY_ID
            value: '3'
          - name: ZOO_PORT
            value: '2181'
          - name: ZOO_SERVERS
            value: server.1=erda-zookeeper-1.{{ .Release.Namespace }}.svc.cluster.local:2888:3888 server.2=erda-zookeeper-2.{{ .Release.Namespace }}.svc.cluster.local:2888:3888 server.3=0.0.0.0:2888:3888
          - name: ZOO_SYNC_LIMIT
            value: '2'
          - name: ZOO_TICK_TIME
            value: '6000'
          - name: ZOO_USER
            value: zookeeper
          - name: POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: HOST_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.hostIP
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | default "0.1" | quote }}
              memory: {{ .Values.resources.requests.memory | default "256Mi" | quote }}
            limits:
              cpu: {{ .Values.resources.limits.cpu |  default "1" | quote }}
              memory: {{ .Values.resources.limits.memory | default "512Mi" | quote }}
          volumeMounts:
          - name: erda-zookeeper-3
            mountPath: /data
          livenessProbe:
            tcpSocket:
              port: 2181
            initialDelaySeconds: 1
            timeoutSeconds: 10
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 9
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      labels:
        app: erda-zookeeper-3
      name: erda-zookeeper-3
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 32Gi
      storageClassName: {{ .Values.storageClassName | default "dice-local-volume" }}
      volumeMode: Filesystem
---
kind: Service
apiVersion: v1
metadata:
  name: erda-zookeeper-1
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: erda-zookeeper-1-tcp-2181
    protocol: TCP
    port: 2181
  - name: erda-zookeeper-1-tcp-2888
    protocol: TCP
    port: 2888
  - name: erda-zookeeper-1-tcp-3888
    protocol: TCP
    port: 3888
  selector:
    app: erda-zookeeper-1
---
kind: Service
apiVersion: v1
metadata:
  name: erda-zookeeper-2
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: erda-zookeeper-2-tcp-2181
    protocol: TCP
    port: 2181
  - name: erda-zookeeper-2-tcp-2888
    protocol: TCP
    port: 2888
  - name: erda-zookeeper-2-tcp-3888
    protocol: TCP
    port: 3888
  selector:
    app: erda-zookeeper-2
---
kind: Service
apiVersion: v1
metadata:
  name: erda-zookeeper-3
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: erda-zookeeper-3-tcp-2181
    protocol: TCP
    port: 2181
  - name: erda-zookeeper-3-tcp-2888
    protocol: TCP
    port: 2888
  - name: erda-zookeeper-3-tcp-3888
    protocol: TCP
    port: 3888
  selector:
    app: erda-zookeeper-3
{{- end }}
