apiVersion: v1
data:
  etcd-ca.pem: ${ETCD_CA}
  etcd-server-key.pem:  ${ETCD_SERVER_KEY}
  etcd-server.pem: ${ETCD_SERVER}
  etcd-peer-key.pem: ${ETCD_PEER_KEY}
  etcd-peer.pem: ${ETCD_PEER}
  etcd-client-key.pem: ${ETCD_CLIENT_KEY}
  etcd-client.pem: ${ETCD_CLIENT}
kind: Secret
metadata:
  name: erda-etcd-server-secret
  namespace: ${ERDA_NAMESPACE}
type: Opaque
