apiVersion: v1
data:
  etcd-ca.pem: ${ETCD_CA}
  etcd-client-key.pem: ${ETCD_CLIENT_KEY}
  etcd-client.pem: ${ETCD_CLIENT}
kind: Secret
metadata:
  name: erda-etcd-client-secret
  namespace: ${ERDA_NAMESPACE}
type: Opaque
