apiVersion: v1
data:
  CLUSTER_DNS: 10.96.0.3
  DICE_CLUSTER_NAME:  {{ .Values.configmap.clustername }}
  DICE_CLUSTER_TYPE: kubernetes
  DICE_HTTP_PORT: {{ .Values.configmap.protocol.port | quote }}
  DICE_INSIDE: "false"
  DICE_IS_EDGE: "false"
  DICE_PROTOCOL:  {{ .Values.configmap.protocol.type }}
  DICE_ROOT_DOMAIN: {{ .Values.configmap.domain }}
  DICE_SIZE:  {{ .Values.configmap.size }}
  DICE_SSH_PASSWORD:  {{ .Values.configmap.ssh.password |default "123123" | quote }}
  DICE_SSH_USER:  {{ .Values.configmap.ssh.user }}
  DICE_STORAGE_MOUNTPOINT: /netdata
  DICE_VERSION: "1.1"
  ETCD_ENDPOINTS: https://erda-etcd.{{ .Values.namespace | default "erda-system" }}.svc.cluster.local:2379
  ETCD_MONITOR_URL: http://erda-etcd.{{ .Values.namespace | default "erda-system" }}.svc.cluster.local:2381
  GLUSTERFS_MONITOR_URL: ""
  IS_FDP_CLUSTER: "false"
  ISTIO_ALIYUN: "false"
  ISTIO_INSTALLED: "true"
  ISTIO_VERSION: 1.1.4
  KUBERNETES_VENDOR: dice
  KUBERNETES_VERSION: {{ .Values.configmap.kubernetes.version }}
  {{- if .Values.configmap.kubernetes.lb }}
  LB_ADDR: {{ .Values.configmap.kubernetes.lb }}
  LB_MONITOR_URL: http://{{ .Values.configmap.kubernetes.lb }}
  {{- end }}
  MASTER_ADDR: {{ .Values.configmap.kubernetes.master }}
  MASTER_MONITOR_ADDR: {{ .Values.configmap.kubernetes.master }}
  MASTER_VIP_ADDR: {{ .Values.configmap.kubernetes.mastervip }}
  MASTER_VIP_URL: https://{{ .Values.configmap.kubernetes.mastervip }}
kind: ConfigMap
metadata:
  name: dice-cluster-info
  namespace: {{ .Values.namespace | default "erda-system" }}
