apiVersion: "db.orange.com/v1alpha1"
kind: "CassandraCluster"
metadata:
  name: erda-cassandra
  namespace: {{ .Values.global.namespace | default "erda-system" }}
  labels:
    cluster: k8s.kaas
spec:
  pod:
    tolerations:
      - operator: Exists
  cassandraImage: {{ .Values.global.image.repository }}/addon-cassandra:{{ .Values.cassandraImageTag}}
  bootstrapImage: registry.erda.cloud/erda/cassandra-bootstrap:0.1.8
  configMapName: erda-cassandra-configmap-v1
  imagepullpolicy: {{ .Values.global.image.imagePullPolicy }}
  {{- if .Values.global.imagePullSecrets }}
  {{- with .Values.global.imagePullSecrets }}
  imagePullSecret:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- end }}
  dataStorageClass: {{ .Values.global.storageClassName | default "dice-local-volume" }}
  {{- if eq .Values.global.size "demo" }}
  dataCapacity: "10Gi"
  {{- else }}
  dataCapacity: {{ .Values.capacity | default "300Gi" }}
  {{- end }}
  hardAntiAffinity: false           # Do we ensure only 1 cassandra on each node ?
  deletePVC: true
  autoPilot: false
  gcStdout: true
  autoUpdateSeedList: false
  maxPodUnavailable: 1
  runAsUser: 999
  backRestSidecar:
    image: registry.erda.cloud/erda/instaclustr-icarus:1.0.9
  resources:
    {{- if eq .Values.global.size "demo" }}
    requests:
      cpu: "0.5"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "4Gi"
    {{- else }}
    requests:
      cpu: {{ .Values.resources.requests.cpu | default "6" | quote }}
      memory: {{ .Values.resources.requests.memory | default "12Gi" }}
    limits:
      cpu: {{ .Values.resources.limits.cpu | default "12" | quote }}
      memory: {{ .Values.resources.limits.memory | default "48Gi" }}
    {{- end}}
  topology:
    dc:
    - name: dc1
      nodesPerRacks: 1
      {{- if eq .Values.global.size "demo" }}
      rack:
      - name: rack1
      {{- else }}
      {{- with .Values.racks }}
      rack:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- end }}
