apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: erda-cassandra-operator
  name: erda-cassandra-operator
  namespace: {{ .Values.global.namespace | default "erda-system" }}
  annotations:
    "helm.sh/hook": pre-install
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: erda-cassandra-operator
  name: cassandra-cluster-node
  namespace: {{ .Values.global.namespace | default "erda-system" }}
  annotations:
    "helm.sh/hook": pre-install
