apiVersion: v1
kind: Service
metadata:
  name: cassandra-operator-metrics
  namespace: {{ .Values.global.namespace | default "erda-system" }}
  labels:
    component: app
    app: cassandra-operator-metrics
spec:
  selector:
    app: erda-cassandra-operator
  ports:
  - name: metrics
    port: 9710
    protocol: TCP
