# Global variable
global:
  # size defines deployment mode: 'demo' for minimal and 'prod' for product.
  size: demo
  # namespace defines which namespace will erda components deployed in Kubernetes.
  namespace: default
  # image defines repository and image pull policy for docker image.
  image:
    # repository defines docker image repository.
    repository: registry.erda.cloud/erda
    # imagePullPolicy defines how to pull images.
    imagePullPolicy: IfNotPresent
  # imagePullSecrets defines pull secrets for pulling image from private image repository.
  imagePullSecrets: [ ]

# tag defines mysql image tag.
tag: 5.7.34
# user defines the username Erda used to access mysql.
user: erda
# database defines the database name Erda used to access mysql.
database: erda
# password defines the password according to the username Erda used to access mysql.
password: password
# storageClassName defines which storageclass to use for creating PV in Kubernetes.
storageClassName: "dice-local-volume"
# capacity defines pvc capacity for myqsl instance  (default: 100Gi for prod mode and 10Gi for demo mode).
capacity:
resources:
  requests:
    cpu:
    memory:
  limits:
    cpu:
    memory:
