apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mysql.name | default "erad-mysql" }}
  namespace: {{ .Values.namespace | default "erda-system" }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.mysql.name | default "erad-mysql" }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.mysql.name | default "erad-mysql" }}
    spec:
      tolerations:
      - operator: Exists
      containers:
      - image: {{ .Values.image.repository }}/{{ .Values.mysql.name | default "erad-mysql" }}:{{ .Values.mysql.version }}
        name: {{ .Values.mysql.name | default "erad-mysql" }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.mysql.password }}
        - name: MYSQL_DATABASE
          value: {{ .Values.mysql.database }}
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
          limits:
            cpu: 1
            memory: 2Gi
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      - name: mysql-initdb
        configMap:
          name: mysql-initdb-config
