# Global variable
global:
  # size defines deployment mode: 'demo' for minimal and 'prod' for product.
  size: demo
  # image defines repository and image pull policy for docker image.
  image:
    # repository defines docker image repository.
    repository: registry.erda.cloud/erda
    # imagePullPolicy defines how to pull images.
    imagePullPolicy: IfNotPresent
  # imagePullSecrets defines pull secrets for pulling image from private image repository.
  imagePullSecrets: [ ]

# tag defines elasticsearch image tag.
tag: 6.2.4
# replicas defines the number of elasticsearch instances in 'prod' deployment mode
replicas: 3
# numberOfMasters defines the number of elasticsearch instances can be as master candidates in 'prod' deployment mode（must more than half of replicas + 1）
numberOfMasters: 2
# # storageClassName defines which storageclass to use for creating PV in Kubernetes.
storageClassName: "dice-local-volume"
# capacity defines pvc capacity for elasticsearch instance  (default: 1000Gi for prod mode and 50Gi for demo mode).
capacity:
# elasticsearch JAVA_OPTS (java heap size suggests to set as 0.75 * resources.limits.memory, eg: "-Xms6144m -Xmx6144m" for resources.limits.memory is 8192Mi)
javaOpts:
# resources defines resources requests and limits for pod
resources:
  requests:
    cpu:
    memory:
  limits:
    cpu:
    memory:
