apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
  namespace: {{ .Release.Namespace }}
data:
  initdb.sql: |
    create user '{{ .Values.user }}dbmigration'@'%' identified by '{{ .Values.password }}';
    create user '{{ .Values.user }}'@'%' identified by '{{ .Values.password }}';
    grant all privileges on *.* to '{{ .Values.user }}dbmigration'@'%' WITH GRANT OPTION;
    grant all privileges on *.* to '{{ .Values.user }}'@'%' WITH GRANT OPTION;
    flush privileges;
