apiVersion: v2
name: zookeeper
description: A Helm chart for zookeeper
type: application
version: 3.4.13
keywords:
  - zookeeper
sources:
  - https://github.com/erda-project/erda-release
maintainers:
  - name: Luobingli
    email: luobily@gmail.com
  - name: Wangzhuzhen
    email: zhuzhenwang1984@gmail.com
  - name: Liutianxiang
    email: root@viper.run