# Global variable
global:
  # size defines deployment mode: 'demo' for minimal and 'prod' for product.
  size: demo
  # image defines repository and image pull policy for docker image.
  image:
    # repository defines docker image repository.
    repository: registry.erda.cloud/erda
    # imagePullPolicy defines how to pull images.
    imagePullPolicy: IfNotPresent
  # imagePullSecrets defines pull secrets for pulling image from private image repository.
  imagePullSecrets: [ ]

# tag defines zookeeper image tag.
tag: 3.4.13-monitor
# storageClassName defines which storageclass to use for creating PV in Kubernetes.
storageClassName: "dice-local-volume"
# capacity defines pvc capacity for zookeeper instance (default: 32Gi for prod mode and 4Gi for demo mode)..
capacity:
# resources defines resources requests and limits for pod
resources:
  requests:
    cpu:
    memory:
  limits:
    cpu:
    memory:
