apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: erda-redis
  namespace: {{ .Values.global.namespace | default "erda-system" }}
spec:
  sentinel:
    image: {{ .Values.global.image.repository }}/addon-redis:{{ .Values.redisFailover.tag }}
    {{- if eq .Values.global.size "prod" }}
    replicas: {{ .Values.redisFailover.sentinel.replicas | default 3 }}
    {{- else }}
    replicas: 1
    {{- end }}
    tolerations:
      - operator: Exists
    affinity:
      nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            {{- if .Values.nodematchExpressions }}
            {{- range $_, $value := .Values.nodematchExpressions }}
              - key: {{ $value.key }}
                operator: {{ $value.operator }}
            {{- end }}
            {{- end }}
    resources:
      requests:
        cpu: {{ .Values.redisFailover.sentinel.resources.requests.cpu | default "50m" | quote }}
        memory: {{ .Values.redisFailover.sentinel.resources.requests.memory | default "64Mi" | quote }}
      limits:
        cpu: {{ .Values.redisFailover.sentinel.resources.requests.cpu | default "200m" | quote }}
        memory: {{ .Values.redisFailover.sentinel.resources.limits.memory | default "256Mi" | quote }}
    customConfig:
    - "down-after-milliseconds 12000"
    - "failover-timeout 12000"
  redis:
    image: {{ .Values.global.image.repository }}/addon-redis:{{ .Values.redisFailover.tag }}
    {{- if eq .Values.global.size "prod" }}
    replicas: {{ .Values.redisFailover.redis.replicas | default 2 }}
    {{- else }}
    replicas: 1
    {{- end }}
    tolerations:
      - operator: Exists
    affinity:
      nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            {{- if .Values.nodematchExpressions }}
            {{- range $_, $value := .Values.nodematchExpressions }}
              - key: {{ $value.key }}
                operator: {{ $value.operator }}
            {{- end }}
            {{- end }}
    resources:
      {{- if eq .Values.global.size "demo" }}
      requests:
        cpu: {{ .Values.redisFailover.redis.resources.requests.cpu | default "100m" | quote }}
        memory: {{ .Values.redisFailover.redis.resources.requests.memory | default "256Mi" | quote }}
      limits:
        cpu: {{ .Values.redisFailover.redis.resources.limits.cpu |  default "200m" | quote }}
        memory: {{ .Values.redisFailover.redis.resources.limits.memory | default "1024Mi" | quote }}
      {{- else }}
      requests:
        cpu: {{ .Values.redisFailover.redis.resources.requests.cpu | default "150m" | quote }}
        memory: {{ .Values.redisFailover.redis.resources.requests.memory | default "1Gi" | quote }}
      limits:
        cpu: {{ .Values.redisFailover.redis.resources.limits.cpu |  default "300m" | quote }}
        memory: {{ .Values.redisFailover.redis.resources.limits.memory | default "2Gi" | quote }}
      {{- end }}
  auth:
    secretPath: erda-redis-auth
