{{- if (include "erda.buildkitd.enabled" .) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "erda.buildkitd.configmapName" . }}
  namespace: {{ .Release.Namespace | quote }}
data:
  buildkitd.toml: |-
    {{- include "erda.buildkitd.configuration" . | nindent 4 -}}
{{- end -}}
