apiVersion: v1
kind: Secret
metadata:
  annotations:
    "helm.sh/hook": pre-install
  name: erda-cluster-credential
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- if .Values.erda.clusterConfig.clusterAccessKey }}
  CLUSTER_ACCESS_KEY: {{ .Values.erda.clusterConfig.clusterAccessKey | b64enc }}
  {{- else }}
  CLUSTER_ACCESS_KEY: aW5pdA==
  {{- end }}