{{- if (include "erda.registry.regcred.enabled" . ) -}}
apiVersion: v1
data:
  .dockerconfigjson: {{ printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.registry.custom.address (printf "%s:%s" .Values.registry.custom.username .Values.registry.custom.password | b64enc) | b64enc }}
kind: Secret
metadata:
  name: regcred
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
{{- end -}}