global:
  size: demo
  namespace: default
  image:
    repository: registry.erda.cloud/erda
    imagePullPolicy: IfNotPresent
  imagePullSecrets: [ ]

tag: 1.0.0-20210416-1a3758f
provisioner:
  local:
    hostpath: /data
  nfs:
    hostpath: /netdata
resources:
  requests:
    cpu: 10m
    memory: 10Mi
  limits:
    cpu: 100m
    memory: 256Mi
