apiVersion: v2
name: registry
description: A Helm chart for registry
type: application
version: 2.7.1
keywords:
  - registry
#home: https://goharbor.io
#icon: https://raw.githubusercontent.com/goharbor/website/master/static/img/logos/harbor-icon-color.png
sources:
  - https://github.com/erda-project/erda-release
maintainers:
  - name: Erda SRE Team