# Global variable
global:
  # size defines deployment mode: 'demo' for minimal and 'prod' for product.
  size: demo
  # image defines repository and image pull policy for docker image.
  image:
    # repository defines docker image repository.
    repository: registry.erda.cloud/erda
    # imagePullPolicy defines how to pull images.
    imagePullPolicy: IfNotPresent
  # imagePullSecrets defines pull secrets for pulling image from private image repository.
  imagePullSecrets: [ ]

# redisOperator defines image tag and resources used by redis operator instance.
redisOperator:
  # tag defines redis operator image tag.
  tag: 1.0.0-20200723-1a7a9f14
  # resources defines resources requests and limits for redis operator pod
  resources:
    requests:
      cpu:
      memory:
    limits:
      cpu:
      memory:

# redisFailover configuration
redisFailover:
  # tag defines redis image tag.
  tag: 3.2.12
  secret: aUVWSUk2TFk2RWJyYzRIWA==
  # redis master-slave standby
  redis:
    # replicas defines the number of redis instance
    replicas:
    # resources defines resources requests and limits for redis instance pod
    resources:
      requests:
        cpu:
        memory:
      limits:
        cpu:
        memory:
  # redis sentinels
  sentinel:
    # replicas defines the number of redis sentinel instance
    replicas:
    # resources defines resources requests and limits for redis sentinel pod
    resources:
      requests:
        cpu:
        memory:
      limits:
        cpu:
        memory:
