# 全局可用参数
global:
  # 部署模式：支持最小化单点部署（demo） 和 高可用部署（prod） 两种模式
  size: demo
  # 组件部署的目标 namespace，如果不存在需要先创建
  namespace: default
  # 镜像参数
  image:
    # 镜像仓库
    repository: registry.erda.cloud/erda
    # 镜像拉取策略
    imagePullPolicy: IfNotPresent
  # 镜像拉取 Secrets
  imagePullSecrets: [ ]
  # 部署组件中 StatefulSet 负载使用的存储的 StorageClass 对象的名称
  storageClassName:


# redisOperator 组件配置
redisOperator:
  # registry 镜像 tag (版本)
  tag: 1.0.0-20200723-1a7a9f14
  resources:
    requests:
      cpu: "10m"
      memory: "50Mi"
    limits:
      cpu: "100m"
      memory: "50Mi"

# redisFailover 组件配置
redisFailover:
  tag: 3.2.12
  secret: aUVWSUk2TFk2RWJyYzRIWA==
  # redis 实例配置
  redis:
    replicas: 2
    resources:
      requests:
        cpu: "150m"
        memory: "1Gi"
      limits:
        cpu: "300m"
        memory: "2Gi"
  # redis sentinel 配置
  sentinel:
    replicas: 3
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"