apiVersion: v2
name: sonar
description: A Helm chart for sonar
type: application
version: 8.4.2
keywords:
  - sonar
sources:
  - https://github.com/erda-project/erda-release
maintainers:
  - name: Luobingli
    email: luobily@gmail.com
  - name: Wangzhuzhen
    email: zhuzhenwang1984@gmail.com
  - name: Liutianxiang
    email: root@viper.run
