# Global variable
global:
  # size defines deployment mode: 'demo' for minimal and 'prod' for product.
  size: demo
  # image defines repository and image pull policy for docker image.
  image:
    # repository defines docker image repository.
    repository: registry.erda.cloud/erda
    # imagePullPolicy defines how to pull images.
    imagePullPolicy: IfNotPresent
  # imagePullSecrets defines pull secrets for pulling image from private image repository.
  imagePullSecrets: [ ]
  # cluster access domain
  domain: erda.io

# tag defines sonar image tag.
tag: 8.4.2
# token defines sonar admin token (base64 encoded)
token: LY9DepZ7iDUsyH8TFoDR85ok7y2nw1
# password defines sonar admin token (base64 encoded)
password: 78tE846484lQQFUwY51h0Yr96ZQ063
# resources defines resources requests and limits for pod
resources:
  requests:
    cpu:
    memory:
  limits:
    cpu:
    memory:
