apiVersion: v2
name: etcd
description: A Helm chart for etcd
type: application
version: 3.3.15
keywords:
  - etcd
sources:
  - https://github.com/erda-project/erda-release
maintainers:
  - name: Luobingli
    email: luobily@gmail.com
  - name: Wangzhuzhen
    email: zhuzhenwang1984@gmail.com
  - name: Liutianxiang
    email: root@viper.run